name: HelperBot
version: @VERSION@
main: me.Delocaz.HelperBot.HelperBot
author: Delocaz
authors: [SweetieBelle]
api-version: 1.19
commands:
    help:
        usage: /<command> <page>
        aliases: [helpme, plzhelp, icanhazhelp, halp]
    addhelp:
        usage: /<command> <page> <content>
    delhelp:
        usage: /<command> <page>